apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData: # write plaintext here, Kubernetes base64 encodes it automatically
  MONGODB_URL: "your_mongodb_connection_string"
  B2_KEY_ID: "your_b2_key"
  B2_APPLICATION_KEY: "your_b2_app_key"
  B2_BUCKET_NAME: "CollegeDrive"
  B2_ENDPOINT_URL: "Your Backblaze B2 endpoint URL"
  SECRET_KEY: "your_jwt_secret"

---
# 2. Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collegedrive-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: collegedrive-backend
  template:
    metadata:
      labels:
        app: collegedrive-backend
    spec:
      containers:
      - name: backend
        image: kmlop/collegedrive-backend:v1
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: backend-secrets # securely loads all the keys

---
# 3. Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: collegedrive-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP